name: serial_port
description: libserialport FFI bindings
version: 0.0.1
homepage: https://github.com/jpnurmi/dart_serial_port
repository: https://github.com/jpnurmi/dart_serial_port
issue_tracker: https://github.com/jpnurmi/dart_serial_port/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
  meta: ^1.1.8

dev_dependencies:
  ffigen: 0.1.5
  test: ^1.15.3
  test_coverage: ^0.4.3

ffigen:
  name: LibSerialPort
  description: >-
    libserialport: cross-platform library for accessing serial ports
  output: 'lib/src/libserialport.dart'
  headers:
    - '/usr/local/include/libserialport.h'
  structs:
    include:
      matches:
        - 'sp_.*'
  compiler-opts: '-I/usr/lib/llvm-7/lib/clang/7.0.1/include'
